### ISSUE TITLE
question about cookie

### ISSUE THREAD

**Issue by Gimenz** [atharahmed/tiktok-private-api#3]
hi, i've used this module for my tiktok downloader, i modified on this [line](https://github.com/atharahmed/tiktok-private-api/blob/a9cef34353810d6a68030cec2880546ee53018db/src/core/state.ts#L8) to add cookies

it useful for fetch data from private account, the cookies i get from account that follows the private account

can you add some option, or any parameter to use cookie.
thanks

**Comment by atharahmed** [comment]
Hi,

Thank you for bringing this up.

I have made an update and now you can append a cookie header in the headers list, here is how to do it:

```
import { TikTokClient } from "tiktok-private-api";

(async () => {
  const scraper = new TikTokClient();
  
  // Update API headers for videos function
  scraper.state.defaultApiHeaders = {
    ...scraper.state.defaultApiHeaders,
    cookie: "name=value",
  };
  
  // Update browser headers for user info function
  scraper.state.defaultHeaders = {
    ...scraper.state.defaultHeaders,
    cookie: "name=value",
  };

  const data = await scraper.user.info("redbull");

  console.log(data);
})();
```

The cookie has to be string like normal browser sends, I'll probably revise this and setup a cookie jar in future but closing the issue for now :)

Thanks!
